// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nktndqzbtvbvddpxxzbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rdG5kcXpidHZidmRkcHh4emJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1ODI2OTQsImV4cCI6MjA2NzE1ODY5NH0.fTdisa_wYIxLJyDHNS6j06YQZFD-fqVjdxr4bsnZgyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});